In [1]:
# Notebook imports and packages
import numpy as np

np.set_printoptions(linewidth=400)

#  Finishing up lesson 50


In [2]:
x = np.array([[0.1, 1.2, 2.4, 3.2, 4.1, 5.7, 6.5]]).T
y = np.array([[1.7, 2.4, 3.5, 3.0, 6.1, 9.4, 8.2]]).T

In [3]:
def mse(y, y_hat):
    return np.average(np.power(y-y_hat,2), axis=0)

## My result for minimum cost

In [8]:
nr_thetas = 2001
th_0 = th_1 = np.linspace(start=-2, stop=4, num=nr_thetas)
plot_t0, plot_t1 = np.meshgrid(th_0, th_1)

print(plot_t0,'\n\n')
print(plot_t1, '\n\n')

[[-2.    -1.997 -1.994 ...  3.994  3.997  4.   ]
 [-2.    -1.997 -1.994 ...  3.994  3.997  4.   ]
 [-2.    -1.997 -1.994 ...  3.994  3.997  4.   ]
 ...
 [-2.    -1.997 -1.994 ...  3.994  3.997  4.   ]
 [-2.    -1.997 -1.994 ...  3.994  3.997  4.   ]
 [-2.    -1.997 -1.994 ...  3.994  3.997  4.   ]] 


[[-2.    -2.    -2.    ... -2.    -2.    -2.   ]
 [-1.997 -1.997 -1.997 ... -1.997 -1.997 -1.997]
 [-1.994 -1.994 -1.994 ... -1.994 -1.994 -1.994]
 ...
 [ 3.994  3.994  3.994 ...  3.994  3.994  3.994]
 [ 3.997  3.997  3.997 ...  3.997  3.997  3.997]
 [ 4.     4.     4.    ...  4.     4.     4.   ]] 




In [9]:
plot_cost = np.zeros((nr_thetas, nr_thetas))

for i in range(nr_thetas):
    for j in range(nr_thetas):
        y_hat = plot_t0[i][j] + plot_t1[i][j]*x
        plot_cost[i][j] = mse(y, y_hat)

print(plot_cost)

[[231.61       231.52883757 231.44769314 ... 105.35752171 105.31232329 105.26714286]
 [231.25242014 231.17131737 231.0902326  ... 105.11913683 105.07399806 105.02887729]
 [230.89512057 230.81407746 230.73305234 ... 104.88103223 104.83595311 104.790892  ]
 ...
 [ 76.33628629  76.37431883  76.41236937 ... 188.23536091 188.30935746 188.383372  ]
 [ 76.53871729  76.57680949  76.61491969 ... 188.55698689 188.63104309 188.70511729]
 [ 76.74142857  76.77958043  76.81775029 ... 188.87889314 188.953009   189.02714286]]


In [10]:
ij_min = np.unravel_index(indices=plot_cost.argmin(), shape=plot_cost.shape)
print(
    f"Minimum value of plot_cost: {plot_cost.min()}",
    f"Position of minimum: {ij_min}",
    f"Best Theta 0: {plot_t0[ij_min]}",
    f"Best Theta 1: {plot_t1[ij_min]}",
    sep='\n'
)


Minimum value of plot_cost: 0.9479680000000004
Position of minimum: (1074, 950)
Best Theta 0: 0.8500000000000001
Best Theta 1: 1.222


## Teacher's result for minimum cost

In [4]:
nr_thetas = 200
th_0 = th_1 = np.linspace(start=-1, stop=3, num=nr_thetas)
plot_t0, plot_t1 = np.meshgrid(th_0, th_1)

plot_cost = np.zeros((nr_thetas, nr_thetas))

for i in range(nr_thetas):
    for j in range(nr_thetas):
        y_hat = plot_t0[i][j] + plot_t1[i][j]*x
        plot_cost[i][j] = mse(y, y_hat)

ij_min = np.unravel_index(indices=plot_cost.argmin(), shape=plot_cost.shape)
print(
    f"Minimum value of plot_cost: {plot_cost.min()}",
    f"Position of minimum: {ij_min}",
    f"Best Theta 0: {plot_t0[ij_min]}",
    f"Best Theta 1: {plot_t1[ij_min]}",
    sep='\n'
)

Minimum value of plot_cost: 0.9483826526747164
Position of minimum: (111, 91)
Best Theta 0: 0.829145728643216
Best Theta 1: 1.2311557788944723
